server:
  port: 8222

# spring
spring:
  application:
    name: springboot-mybatis
#  profiles:
#    active: prod

#spring:
  # 配置数据库信息
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   # 指定数据源为druid
    druid:
      # 数据源配置
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/db_test?serverTimezone=GMT%2B8&characterEncoding=UTF-8&useSSL=false  # 设置时区
      username: root
      password: root
      # 初始化 最小 最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置多个英文逗号分隔
      filters: stat,wall
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      # 是否启用StatFilter默认值true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: false
        session-stat-max-count: 1000
        principal-cookie-name: admin
        principal-session-name: admin
        profile-enable: true
      # 根据配置中的url-pattern来访问内置监控页面，如果是上面的配置，内置监控页面的首页是/druid/index.html
      # http://loacalhsot:8081/druid
      stat-view-servlet:
        url-pattern: /druid/*  # 监控页面访问路径
        # 允许清空统计数据
        reset-enable: true
        login-username: admin
        login-password: 123456
        # StatViewSerlvet展示出来的监控信息比较敏感，是系统运行的内部情况，如果你需要做访问控制，可以配置allow和deny这两个参数
        # deny优先于allow，如果在deny列表中，就算在allow列表中，也会被拒绝。如果allow没有配置或者为空，则允许所有访问
        # 配置的格式
          # <IP>
          # 或者<IP>/<SUB_NET_MASK_size>其中128.242.127.1/24
          # 24表示，前面24位是子网掩码，比对的时候，前面24位相同就匹配,不支持IPV6。
        allow:
        deny:


#jdbc.driverClassName: com.mysql.cj.jdbc.Driver
#jdbc.url: jdbc:mysql://localhost:3306/db_test?serverTimezone: GMT
#jdbc.username: root
#jdbc.password: root


#spring.datasource.type: com.alibaba.druid.pool.DruidDataSource
#spring.datasource.url: jdbc:mysql://localhost:3306/db_test?serverTimezone=GMT
#spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
#spring.datasource.username: root
#spring.datasource.password: root


## Hikari
#spring.datasource.hikari.idle-timeout: 60000
#spring.datasource.hikari.maximum-pool-size: 30
#spring.datasource.hikari.minimum-idle: 10


## Alibaba Druid
#初始化连接数
#spring.datasource.druid.initial-size: 1
#最小空闲连接
#spring.datasource.druid.min-idle: 1
#最大活动连接
#spring.datasource.druid.max-active: 20
#获取连接时测试是否可用
#spring.datasource.druid.test-on-borrow: true
#监控页面启动
#spring.datasource.druid.stat-view-servlet.allow: true


#初始化时建立物理连接的个数
#spring.datasource.druid.initial-size: 3
#最小连接池数量
#spring.datasource.druid.min-idle: 3
#最大连接池数量
#spring.datasource.druid.max-active: 10
#获取连接时最大等待时间
#spring.datasource.druid.max-wait: 60000
#配置监控页面访问登录名称
#spring.datasource.druid.stat-view-servlet.login-username: root
#配置监控页面访问密码
#spring.datasource.druid.stat-view-servlet.login-password: root
#是否开启慢sql查询监控
#spring.datasource.druid.filter.stat.log-slow-sql: true
#慢SQL执行时间
#spring.datasource.druid.filter.stat.slow-sql-millis: 1


## Mybatis
mybatis:
  type-aliases-package: model
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true



# 开启Spring Boot优雅关闭
management.endpoint.shutdown.enabled: on
# 暴露shutdown端点
management.endpoints.web.exposure.include: shutdown
# 自定义管理端点的前缀(保证安全)
management.endpoints.web.base-path: /me-actuator
# 自定义actuator端口
management.server.port: 12581
# 不允许远程管理连接(不允许外部调用保证安全)
management.server.address: 127.0.0.1

management:
  health:
    consul:
      enabled: false
    defaults:
      enabled: false

health:
  config:
    enabled: false
  sleuth:
    log:
      json:
        enabled: false
      slf4j:
        enabled: false

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  refresh:
    enabled: false


