server:
  port: 8222

#spring
spring:
  application:
    name: springboot-mybatis

    
spring.datasource.url: jdbc:mysql://localhost:3306/db_test?serverTimezone=GMT
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.username: root
spring.datasource.password: root


# 配置资源文件的路径（properties写了中文会给转码。所以这里只是显示在博客上，github上不出现这句）
# Configuring the path of a resource file
#mybatis.config-locations: classpath:mybatis/sqlMapConfig.xml
#mybatis.mapper-locations: classpath:mybatis/mapper/*.xml
#mybatis.type-aliases-package: model  

mybatis:
  type-aliases-package: model
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true

